### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by bfirsh** [arxiv-vanity/arxiv-vanity#66]
- [x] remove basic auth
- [x] rerender pages that are on random loop on home page
- [x] post to HN
- [x] tweet
